# common/__init__.py
# Explicit imports

from .text import (
    normalize_text,
    clean_whitespace,
    tokenize,
    unique_tokens,
    join_text_parts,
    extract_candidate_text,
    contains_phrase,
)
from .streaming import stream_candidates
from .dates import parse_date, months_between, years_between, is_present
from .regex import (
    EMAIL_RE,
    PHONE_RE,
    URL_RE,
    LINKEDIN_RE,
    GITHUB_RE,
    YEARS_EXPERIENCE_RE,
    VERSION_RE,
    WORD_RE,
    WHITESPACE_RE,
    find_email,
    find_phone,
    find_linkedin,
    find_github,
    find_urls,
    extract_years,
    has_email,
    has_phone,
    has_github,
    has_linkedin,
)
from .math_utils import (
    clamp,
    normalize,
    safe_divide,
    weighted_average,
    bell_curve,
    log_normalize,
    cosine_similarity,
)
from .logging_utils import configure_logger, get_logger
from .constants import (
    MIN_SCORE,
    MAX_SCORE,
    MIN_CONF,
    MAX_CONF,
    TIERS,
    T_A,
    T_B,
    T_C,
    T_D,
    T_E,
    DIR,
    REL,
    IMP,
    REQ,
    PREF,
    ACT,
    INACT,
    OTW,
    BATCH,
    ENC,
    COLS,
    F_JD,
    F_PROD,
    F_MKT,
    F_HIRE,
    F_CONS,
    F_EXP,
    F_PREF,
    F_PEN,
    ALL_F,
)
from .io import read_json, write_json, read_text, write_text
from .timing import Timer, timed_section

__all__ = [
    # text
    "normalize_text",
    "clean_whitespace",
    "tokenize",
    "unique_tokens",
    "join_text_parts",
    "extract_candidate_text",
    "contains_phrase",
    # streaming
    "stream_candidates",
    # dates
    "parse_date",
    "months_between",
    "years_between",
    "is_present",
    # regex
    "EMAIL_RE",
    "PHONE_RE",
    "URL_RE",
    "LINKEDIN_RE",
    "GITHUB_RE",
    "YEARS_EXPERIENCE_RE",
    "VERSION_RE",
    "WORD_RE",
    "WHITESPACE_RE",
    "find_email",
    "find_phone",
    "find_linkedin",
    "find_github",
    "find_urls",
    "extract_years",
    "has_email",
    "has_phone",
    "has_github",
    "has_linkedin",
    # math
    "clamp",
    "normalize",
    "safe_divide",
    "weighted_average",
    "bell_curve",
    "log_normalize",
    "cosine_similarity",
    # logging
    "configure_logger",
    "get_logger",
    # constants
    "MIN_SCORE",
    "MAX_SCORE",
    "MIN_CONF",
    "MAX_CONF",
    "TIERS",
    "T_A",
    "T_B",
    "T_C",
    "T_D",
    "T_E",
    "DIR",
    "REL",
    "IMP",
    "REQ",
    "PREF",
    "ACT",
    "INACT",
    "OTW",
    "BATCH",
    "ENC",
    "COLS",
    "F_JD",
    "F_PROD",
    "F_MKT",
    "F_HIRE",
    "F_CONS",
    "F_EXP",
    "F_PREF",
    "F_PEN",
    "ALL_F",
    # io
    "read_json",
    "write_json",
    "read_text",
    "write_text",
    # timing
    "Timer",
    "timed_section",
]